# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: ./

jobs:
# Please do not rename this job
  build-project:
    name: build wallet-app
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # if you add permissions here this needs to be done in the wallet-app-orchestration.yaml as well
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Render templates
        uses: ionos-deploy-now/template-renderer-action@v2
        id: template
        with:
          input-directory: .deploy-now/wallet-app
          output-directory: ${{ env.DEPLOYMENT_FOLDER }}
          intermediate-data-file: ${{ env.DEPLOYMENT_FOLDER }}/.template-renderer-data

      - name: Setup composer
        uses: shivammathur/setup-php@v2
        with:
          php_version: '8.2'
          tools: composer:2

      - name: Run composer install
# uncomment the following lines if you want to add environment variables for this step
#        env:
#          MY_ENV_VAR: value-for-my-env-var
#          MY_SECRET_ENV_VAR: ${{ secrets.MY_SECRET }} # here you can find information how to create secrets: https://docs.github.com/en/actions/security-guides/encrypted-secrets
        run: composer install --optimize-autoloader --no-dev

      - name: Build PHP assets
# uncomment the following lines if you want to add environment variables for this step
#        env:
#          MY_ENV_VAR: value-for-my-env-var
#          MY_SECRET_ENV_VAR: ${{ secrets.MY_SECRET }} # here you can find information how to create secrets: https://docs.github.com/en/actions/security-guides/encrypted-secrets
        run: php artisan key:generate --force -n

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: v22.x

      - name: Build Node assets
        env:
          APP_FAKER_LOCALE: es_ES
          APP_FALLBACK_LOCALE: es
          APP_LOCALE: es
          APP_NAME: ISSC-Wallet
          APP_URL: https://wallet.issc.es
          CI: true
          DB_CONNECTION: mysql
          DB_DATABASE: dbs12942190
          DB_HOST: db5015875237.hosting-data.io
          DB_PASSWORD: 5SaYD+nWA8$*f$8
          DB_USERNAME: dbu2438146
          MAIL_ENCRYPTION: null
          MAIL_FROM_ADDRESS: "wallet@israel.name"
          MAIL_FROM_NAME: ISSC-Wallet
          MAIL_HOST: sandbox.smtp.mailtrap.io
          MAIL_MAILER: smtp
          MAIL_PASSWORD: ace416971d3ea0
          MAIL_PORT: 2525
          MAIL_USERNAME: 47e63de01ff7d3
          SITE_URL: ${{ inputs.site-url }}
        run: |
          npm ci
          npm run build

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: c64c7ab6-aedb-4c12-b4f6-0b5b04bb46f7
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/wallet-app/config.yaml
          action: upload
